import type { TourStep } from "../../types/interfaces";

// توضیحات
// -----------------------------------------------------------------
// جناب حریقی برای تغیر موارد آموزش این موارد رو لحاظ بفرماید:برای عنوان آموزش مقادیر داخل تایتل رو تغیر بدید هر دو به زبان فارسی و انگلیسی هستن
// برتی تغیر توضیحات آموزشی دیسکریپشن هارو تغیر بدید که هر دو به زبان فارسی و انگلیسی هستن
// آیدی و المنت تغیر نکند
// ----------------------------------------------------------------

export const tourSteps: TourStep[] = [
  {
    id: "dashboard",
    element: ".step-pass-account",
    side: "bottom",
    title: {
      fa: "تست1",
      en: "test1",
    },
    description: {
      fa: "توضیحات تست",
      en: "desc1 test",
    },
  },
  {
    id: "chart",
    element: ".step-support",
    side: "left",
    title: {
      fa: "تست2",
      en: "test2",
    },
    description: {
      fa: "اینجا عملکرد معاملات نمایش داده می‌شود.",
      en: "Your trading performance is shown here.",
    },
  },
  {
    id: "test3",
    element: ".step-mentor",
    side: "right",
    title: { fa: "تست3", en: "test3" },
    description: { fa: "توضیحات تست3", en: "desc3 test" },
  },
  {
    id: "test4",
    element: ".step-education",
    side: "top",
    title: { fa: "تست4", en: "test4" },
    description: { fa: "توضیحات تست4", en: "desc4 test" },
  },
  {
    id: "test5",
    element: ".step-test5",
    side: "bottom",
    title: { fa: "تست5", en: "test5" },
    description: { fa: "توضیحات تست5", en: "desc5 test" },
  },
  {
    id: "test6",
    element: ".step-test6",
    side: "left",
    title: { fa: "تست6", en: "test6" },
    description: { fa: "توضیحات تست6", en: "desc6 test" },
  },
  {
    id: "test7",
    element: ".step-test7",
    side: "right",
    title: { fa: "تست7", en: "test7" },
    description: { fa: "توضیحات تست7", en: "desc7 test" },
  },
  {
    id: "test8",
    element: ".step-test8",
    side: "top",
    title: { fa: "تست8", en: "test8" },
    description: { fa: "توضیحات تست8", en: "desc8 test" },
  },
  {
    id: "test9",
    element: ".step-test9",
    side: "bottom",
    title: { fa: "تست9", en: "test9" },
    description: { fa: "توضیحات تست9", en: "desc9 test" },
  },
  {
    id: "test10",
    element: ".step-test10",
    side: "left",
    title: { fa: "تست10", en: "test10" },
    description: { fa: "توضیحات تست10", en: "desc10 test" },
  },
  {
    id: "test11",
    element: ".step-test11",
    side: "right",
    title: { fa: "تست11", en: "test11" },
    description: { fa: "توضیحات تست11", en: "desc11 test" },
  },
  {
    id: "test12",
    element: ".step-test12",
    side: "top",
    title: { fa: "تست12", en: "test12" },
    description: { fa: "توضیحات تست12", en: "desc12 test" },
  },
  {
    id: "test13",
    element: ".step-test13",
    side: "bottom",
    title: { fa: "تست13", en: "test13" },
    description: { fa: "توضیحات تست13", en: "desc13 test" },
  },
  {
    id: "test14",
    element: ".step-test14",
    side: "left",
    title: { fa: "تست14", en: "test14" },
    description: { fa: "توضیحات تست14", en: "desc14 test" },
  },
  {
    id: "test15",
    element: ".step-test15",
    side: "right",
    title: { fa: "تست15", en: "test15" },
    description: { fa: "توضیحات تست15", en: "desc15 test" },
  },
  {
    id: "test16",
    element: ".step-test16",
    side: "top",
    title: { fa: "تست16", en: "test16" },
    description: { fa: "توضیحات تست16", en: "desc16 test" },
  },
  {
    id: "test17",
    element: ".step-test17",
    side: "bottom",
    title: { fa: "تست17", en: "test17" },
    description: { fa: "توضیحات تست17", en: "desc17 test" },
  },
  {
    id: "test18",
    element: ".step-test18",
    side: "bottom",
    title: { fa: "تست17", en: "test18" },
    description: { fa: "توضیحات تست18", en: "desc18 test" },
  },
  {
    id: "test19",
    element: ".step-test19",
    side: "left",
    title: { fa: "تست19", en: "test19" },
    description: { fa: "توضیحات تست19", en: "desc19 test" },
  },
  {
    id: "test20",
    element: ".step-test20",
    side: "right",
    title: { fa: "تست20", en: "test20" },
    description: { fa: "توضیحات تست20", en: "desc20 test" },
  },
  {
    id: "test21",
    element: ".step-test21",
    side: "top",
    title: { fa: "تست21", en: "test21" },
    description: { fa: "توضیحات تست21", en: "desc21 test" },
  },
  {
    id: "test22",
    element: ".step-test22",
    side: "bottom",
    title: { fa: "تست22", en: "test22" },
    description: { fa: "توضیحات تست22", en: "desc22 test" },
  },
  {
    id: "test23",
    element: ".step-test23",
    side: "left",
    title: { fa: "تست23", en: "test23" },
    description: { fa: "توضیحات تست23", en: "desc23 test" },
  },
  {
    id: "test24",
    element: ".step-test24",
    side: "right",
    title: { fa: "تست24", en: "test24" },
    description: { fa: "توضیحات تست24", en: "desc24 test" },
  },
  {
    id: "test25",
    element: ".step-test25",
    side: "top",
    title: { fa: "تست25", en: "test25" },
    description: { fa: "توضیحات تست25", en: "desc25 test" },
  },
  //   {
  //     id: "test26",
  //     element: ".step-test26",
  //     side: "bottom",
  //     title: { fa: "تست26", en: "test26" },
  //     description: { fa: "توضیحات تست26", en: "desc26 test" },
  //   },
  //   {
  //     id: "test27",
  //     element: ".step-test27",
  //     side: "left",
  //     title: { fa: "تست27", en: "test27" },
  //     description: { fa: "توضیحات تست27", en: "desc27 test" },
  //   },
  {
    id: "test28",
    element: ".step-test28",
    side: "right",
    title: { fa: "تست28", en: "test28" },
    description: { fa: "توضیحات تست28", en: "desc28 test" },
  },
  {
    id: "test29",
    element: ".step-test29",
    side: "top",
    title: { fa: "تست29", en: "test29" },
    description: { fa: "توضیحات تست29", en: "desc29 test" },
  },
  {
    id: "test30",
    element: ".step-test30",
    side: "bottom",
    title: { fa: "تست30", en: "test30" },
    description: { fa: "توضیحات تست30", en: "desc30 test" },
  },
  {
    id: "test31",
    element: ".step-test31",
    side: "left",
    title: { fa: "تست31", en: "test31" },
    description: { fa: "توضیحات تست31", en: "desc31 test" },
  },
  {
    id: "test32",
    element: ".step-test32",
    side: "right",
    title: { fa: "تست32", en: "test32" },
    description: { fa: "توضیحات تست32", en: "desc32 test" },
  },
  {
    id: "test33",
    element: ".step-test33",
    side: "top",
    title: { fa: "تست33", en: "test33" },
    description: { fa: "توضیحات تست33", en: "desc33 test" },
  },
  {
    id: "test34",
    element: ".step-test34",
    side: "bottom",
    title: { fa: "تست34", en: "test34" },
    description: { fa: "توضیحات تست34", en: "desc34 test" },
  },
  {
    id: "test35",
    element: ".step-test35",
    side: "left",
    title: { fa: "تست35", en: "test35" },
    description: { fa: "توضیحات تست35", en: "desc35 test" },
  },
  {
    id: "test36",
    element: ".step-test36",
    side: "right",
    title: { fa: "تست36", en: "test36" },
    description: { fa: "توضیحات تست36", en: "desc36 test" },
  },
  {
    id: "test37",
    element: ".step-test37",
    side: "top",
    title: { fa: "تست37", en: "test37" },
    description: { fa: "توضیحات تست37", en: "desc37 test" },
  },
  {
    id: "test38",
    element: ".step-test38",
    side: "bottom",
    title: { fa: "تست38", en: "test38" },
    description: { fa: "توضیحات تست38", en: "desc38 test" },
  },
  {
    id: "test39",
    element: ".step-test39",
    side: "left",
    title: { fa: "تست39", en: "test39" },
    description: { fa: "توضیحات تست39", en: "desc39 test" },
  },
  {
    id: "test40",
    element: ".step-test40",
    side: "right",
    title: { fa: "تست40", en: "test40" },
    description: { fa: "توضیحات تست40", en: "desc40 test" },
  },
  {
    id: "test41",
    element: ".step-test41",
    side: "top",
    title: { fa: "تست41", en: "test41" },
    description: { fa: "توضیحات تست41", en: "desc41 test" },
  },
  {
    id: "test42",
    element: ".step-test42",
    side: "bottom",
    title: { fa: "تست42", en: "test42" },
    description: { fa: "توضیحات تست42", en: "desc42 test" },
  },
  {
    id: "test43",
    element: ".step-test43",
    side: "left",
    title: { fa: "تست43", en: "test43" },
    description: { fa: "توضیحات تست43", en: "desc43 test" },
  },
  {
    id: "test44",
    element: ".step-test44",
    side: "right",
    title: { fa: "تست44", en: "test44" },
    description: { fa: "توضیحات تست44", en: "desc44 test" },
  },
  {
    id: "test45",
    element: ".step-test45",
    side: "top",
    title: { fa: "تست45", en: "test45" },
    description: { fa: "توضیحات تست45", en: "desc45 test" },
  },
  {
    id: "test46",
    element: ".step-test46",
    side: "bottom",
    title: { fa: "تست46", en: "test46" },
    description: { fa: "توضیحات تست46", en: "desc46 test" },
  },
  {
    id: "test47",
    element: ".step-test47",
    side: "left",
    title: { fa: "تست47", en: "test47" },
    description: { fa: "توضیحات تست47", en: "desc47 test" },
  },
  {
    id: "test48",
    element: ".step-test48",
    side: "right",
    title: { fa: "تست48", en: "test48" },
    description: { fa: "توضیحات تست48", en: "desc48 test" },
  },
  {
    id: "test49",
    element: ".step-test49",
    side: "top",
    title: { fa: "تست49", en: "test49" },
    description: { fa: "توضیحات تست49", en: "desc49 test" },
  },
  {
    id: "test50",
    element: ".step-test50",
    side: "bottom",
    title: { fa: "تست50", en: "test50" },
    description: { fa: "توضیحات تست50", en: "desc50 test" },
  },
];
